- client/ayon_unreal/plugins/load/load_animation.py
> [!NOTE]
> This is port of https://github.com/ynput/ayon-core/pull/581 from ayon-core. For comments and review notes, please have a look at the conversation in the original PR.
Implemented a standalone loader for animation that do not require a layout to be loaded first.
Loader for Animation in Unreal is heavily based on the original solution using Blender and Unreal. Animation published from Maya doesn't have that layout json and so loading such animation will fail.
> Unreal: Standalone loader for animation

- client/ayon_unreal/ui/splash_screen.py
Use QScreen over QDesktop which is fully deprecated in PySide6.
> Chore: Fix PySide2 and PySide6 compatibility

- client/ayon_unreal/api/pipeline.py
There was an extra comma in `generate_sequence` that blocked any loader that needs to use that function.
Try loading a layout. It should work fine.
> Fix extra comma in generate_sequence

- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
Add option for abc conversion preset in AYON Loader 
Should be also fixing flips UV of the abc import.
Links to: https://github.com/ynput/ayon-maya/pull/12
2. Load Model/StaticMesh/SkeletalMesh
3. Choose your option(by default maya)
> Maya Preset for alembic loaders

- .gitmodules
- client/ayon_unreal/api/rendering.py
- client/ayon_unreal/plugins/create/create_render.py
Resolve https://github.com/ynput/ayon-unreal/issues/11 where blackscreen is rendered.
- Instead of using the level created along with the instance, the local render function would always use the persistent level for rendering if the level from the render instance is not persistent
- This ticket adds the check on the selection for the instance data asset. If the users dont choose the instance data for rendering, it will show the popup menu.
- This ticket also adds new function to find the current level in render creator while some backward compatibility implemented for the deprecated functions in or after UE 5.3
**We should think if checking and raising the error for the current level not being persistent, instead of using the current level when the master level is not persistent.**
- …
> Local Rendering Bug Fix and add backward compatibility for deprecated function in render creator

- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
This PR is to add support for creating/finding materials in alembic import.
Extra support for #21 (we may not need this)
Please test along with this PR: https://github.com/ynput/ayon-maya/pull/37
1. Launch Maya
2. Create Model/Point Cache
3. Make sure the write face sets turned on
4. Publish
5. Loaded the model in Unreal
6. There should be multiple material slots if there are materials/shaders assigned.
> Add supports for material import in alembic loader

- client/ayon_unreal/plugins/load/load_animation.py
Resolve https://github.com/ynput/ayon-unreal/issues/41
You should load your rig before loading animation asset from the fbx animation loader.
2. Load FBX animation
3. Place the asset as the actor
4. The actor should be at correct rotation
> Loading animation asset from FBX animation loader should be in correct rotation

- client/ayon_unreal/plugins/load/load_layout.py
- server/settings.py
Resolve https://github.com/ynput/ayon-unreal/issues/6 in unreal
we need to resolve the maya part too once the load layout json implemented in maya
1. Build Unreal Addon with this branch
2. Set your preferred loaded extension in `ayon+settings://unreal/loaded_assets_extension`
3. Launch Unreal
4. Ayon -> Load
5. Click the memo icon in Load Layout(json)
6. Load your preferred loaded extension format (if you dont think the one you set in ayon server)
7. Click "ok"
> add loaded asset extensions settings for layout loaders in unreal host

- client/ayon_unreal/addon.py
- client/ayon_unreal/ue_workers.py
> [!NOTE]
> This is port of https://github.com/ynput/ayon-core/pull/601 from ayon-core to the new repo. For comments and review notes, please have a look at the conversation in the original PR.
Setting `AYON_UNREAL_PLUGIN` will override now inbuilt integration. Also fixing type issue with source plugin path.
1. set `AYON_UNREAL_PLUGIN` to your local copy of https://github.com/ynput/ayon-unreal-plugin
2. *OPTIONAL:* delete existing plugin from Unreal Engine
3. run Unreal on AYON project
> Fixes for custom integration plugin path

- client/ayon_unreal/plugins/load/load_layout.py
Layout in Unreal supported just `rig` and `model` product types. This is adding also `staticMesh` and `skeletonMesh`.
- Publish `skeletalMesh` and `staticMesh` products
- Create Layout with them and publish it
- Load it in Unreal
> Add `staticMesh` product type to loader plugin

- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_animation.py
- client/ayon_unreal/plugins/load/load_geometrycache_abc.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_fbx.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
Resolve https://github.com/ynput/ayon-unreal/issues/49
Only implemented in the staticMesh, skeletalMesh, animation and geometry cache loader.
We should think if it is neccessary for other loaders too.
2. Load staticMesh, skeletalMesh, animation or geometry cache product
3. It should be located in `/Ayon/Assets/{folder_task_name}/{subset}_{version}_{ext}`
> Add extension as suffix when creating unique asset name

- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_geometrycache_abc.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
- server/settings.py
Resolve https://github.com/ynput/ayon-unreal/issues/50 by adding new setting for alembic conversion in ayon server.
Please build and install unreal addon for this PR
1. Install the unreal addon in ayon server after the build
2. Go to `ayon+settings://unreal/abc_conversion_preset` in unreal ayon settings to set your own presets
3. Launch Unreal
4. Load any product type with abc as extension
5. Setting version with the loaded assets in scene inventory
> Supports for preset almebic conversion import in ayon settings

- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_animation.py
Resolve https://github.com/ynput/ayon-unreal/issues/51
n/a
Should be merged after: https://github.com/ynput/ayon-unreal/pull/54
2. Load Animation product with fbx animation loader
3. Setting version
4. Should have separate version folders/not overwrite the product version as if other imported assets from other loaders
> Setting Version for animation product loaded assets would have exclusive version folders

- client/ayon_unreal/api/pipeline.py
- client/ayon_unreal/plugins/create/create_render.py
- client/ayon_unreal/plugins/publish/collect_render_instances.py
- client/ayon_unreal/plugins/publish/validate_sequence_frames.py
When we create render instance with pre-hierarchy options enabled, it will raise the error and the system can't manage to find the correct path. This PR is to fix it.
We should allow user settings for the sequences path
Resolve #58 
1. Create some level sequences inside `/Game/Ayon/Sequences/`
2. Create Render Instance with pre-hierarchy
3. Should not be error out
Also testing the steps below: 
1. Produce any rendered frames via ```AYON>Render``` (by render instance)
2. Use "Publish" with that render
3. Publishing fails on integration part
> Fix the incorrect sequence path when using pre-hierarchy for render creator

- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_geometrycache_abc.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
Resolve https://github.com/ynput/ayon-unreal/issues/24 and also align to load skeletalmesh according to db.
n/a
2. Load PointCache with `Import Alembic Point Cache` and `Import Alembic Skeletal Mesh`
3. Frame range should be correct
> UnrealAlembicPointCacheLoader/SkeletalMeshLoader: Align the loaded frame range to db

- client/ayon_unreal/plugins/inventory/update_actors.py
Resolve https://github.com/ynput/ayon-unreal/issues/61
This PR is to add pointcache/animation support of replacing all/selected actors as inventory actions.
It does not support for the loaded asset from fbx animation loaders if users want to replace actors in animation families.
2. Load pointcache/animation/rig/model assets
3. Load some assets
4. Go to Ayon -> Manage
5. Use inventory action below
> Add animation/pointcache families support in replacing actors actions

- client/ayon_unreal/api/pipeline.py
Resolve https://github.com/ynput/ayon-unreal/issues/59
Level Sequence should set the frame ranges accordingly to the clipIn & clipOut value set in the folder hierarchies in the project editor(See the screenshot below)
Also tested with camera loader and layout loader
The hardcoded naming should be resolved in the template setting PR: https://github.com/ynput/ayon-unreal/pull/57
2. Ayon -> Generate Sequence Hierarchy
3. Click in the level sequence form where you click to generate the sequence hierarchy
4. The Clip In and Clip Out value should be set accordingly to how we set in the project editor
> make sure the hierarchy_dir is correct when generating sequence

- client/ayon_unreal/api/plugin.py
- client/ayon_unreal/plugins/load/load_uasset.py
Make sure the instance members are always list value
Related issue: https://github.com/ynput/ayon-unreal/issues/65, https://github.com/ynput/ayon-unreal/issues/64, https://github.com/ynput/ayon-unreal/issues/63
Please the PR along with this ticket https://github.com/ynput/ayon-core/pull/859
And with this setting below or with the backend ticket https://github.com/ynput/ayon-backend/pull/328.
```
name: unrealuasset
directory: {root[work]}/{project[name]}/{hierarchy}/{folder[name]}/publish/{product[type]}/{product[name]}/{@version}
filename: {originalBasename}.{ext}
```
<strike>***There are some limitations for loading the uasset/umap btw. You need to perform "delete" the files manually to make it visible. (which is strange)</strike> …
> Make sure instance members are always list value for publishing uasset/Uasset loader can load the uasset

- client/ayon_unreal/api/plugin.py
- client/ayon_unreal/plugins/create/create_staticmeshfbx.py
- client/ayon_unreal/plugins/publish/collect_instance_members.py
- client/ayon_unreal/plugins/publish/extract_fbx.py
- client/ayon_unreal/plugins/publish/validate_model_content.py
This PR is to add missing fbx extractor for staticMesh product type and also use `staticMesh` as product type instead of `unrealStaticMesh` to align with the unreal workflow to other dccs
We need to discuss the use case of this product type in Unreal to other DCCs
1. Select Asset and create staticmesh instance
2. Publish
> Add missing extractor for staticmesh product type

- client/ayon_unreal/hooks/pre_workfile_preparation.py
- server/settings.py
+ Added option in studio settings to allow/disallow project creation for artists
+ Added functionality to project creation
This is usefull when working with source controll like perforce. This way artists dont accidentally create duplicate projects that can't be merged after. Default state is 'enabled' so that it wont change anything when not specificly set to false.
> enhancement: allow project creation option

- client/ayon_unreal/plugins/load/load_camera.py
This PR is to fix the error encountered during setting version and deleting items with the loaded camera assets.
Resolve https://github.com/ynput/ayon-unreal/issues/81
1. Load Camera
2. Set Version 
3. Delete Version
> Camera Loader can set version and delete version

- client/ayon_unreal/plugins/load/load_camera.py
This PR is to add switch version support for camera loader
Resolve #87 
n/a
1. Load Camera
2. Go to Ayon -> Manage
3. Right Click the camera instance-> Switch Folder
4. Should be working
> Supports switch version for camera loader

- client/ayon_unreal/plugins/load/load_layout.py
Resolve https://github.com/ynput/ayon-unreal/issues/93
This PR is to ensure temp map has been removed and the default level should be loaded after removing the asset from layout product type.
n/a
1. Load Layout
2. Delete Layout with scene inventory
3. Default Level Path should be loaded.
> Temp map should be removed after removing layout product type

- client/ayon_unreal/plugins/load/load_layout.py
- server/settings.py
Resolve https://github.com/ynput/ayon-unreal/issues/97
This PR is to introduce the optional setting for deleting the loaded assets when removing layouts.
n/a
1. Build addon with this branch
2. Install addon
3. Go to `ayon+settings://unreal/remove_loaded_assets` to turn on/off the toggle
4. Load Layout
5. Ayon -> Manage
6. Perform `Remove items` upon the layout with the inventory tool
> Make deletion of the loaded assets as optional when removing layout product type

- client/ayon_unreal/api/lib.py
Add debug log to check skeletal mesh component when connecting alembic animation to level sequence performed. This is to make sure the unreal would look at the correct data for switching the skeletal mesh
n/a
1.Load Layout
2. Ayon -> Manage
3. Select animation(abc) and layout elements
4. Right click -> Actions -> Connecting Alembic Animation to Level Sequence
> Checking skeletal mesh component when connecting alembic animation to level sequence performed

- client/ayon_unreal/api/pipeline.py
This PR is to add version number into the asset name and fixes https://github.com/ynput/ayon-unreal/issues/96
The name of the asset would be `asset_testMain_v001_abc` instead of `asset_testMain_abc`
n/a
2. Load assets
> Add version number into the asset name

- client/ayon_unreal/api/lib.py
- client/ayon_unreal/plugins/inventory/connect_animation_to_sequence.py
This PR is to rename the name of the camera actor with version number after users performing connect fbx/alembic animation to level sequence
Possibly Resolve https://github.com/ynput/ayon-unreal/issues/116
n/a
2. Load layout, load camera, load animation
3. Ayon -> Manage -> Actions -> Connect fbx/alembic animation to level sequence
> Make sure the camera actor has name with version number with connect action

- client/ayon_unreal/plugins/load/load_animation.py
This PR is to tell unreal to use the frame range from the published data when importing animation to unreal
n/a
2. Import fbx animation
3. Should be set the frame range of the animation correctly
> Use set range for setting up animation range for fbx animation import

- client/ayon_unreal/api/pipeline.py
- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_animation.py
- client/ayon_unreal/plugins/load/load_geometrycache_abc.py
- client/ayon_unreal/plugins/load/load_image_png.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_fbx.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
- client/ayon_unreal/plugins/load/load_uasset.py
- client/ayon_unreal/plugins/load/load_yeticache.py
- server/settings.py
This PR is to refactor the `format_asset_directory` function so that users can have more freedom to customize their directories for loading the assets.
n/a
1. Build and install the unreal addon with this branch
2. Launch Unreal
3. Change your loaded asset template to your own preferences in `ayon+settings://unreal/loaded_asset_dir` in ayon setting
4. Load Assets
> Refactoring the format asset directory function

- client/ayon_unreal/plugins/load/load_layout_existing.py
This PR is to make sure all spawned actors which are loaded from layout existing loader should be added as binding object into level seqenece  for the layout product type
Resolve https://github.com/ynput/ayon-unreal/issues/121
n/a
2. Load Layout
3. Save
4. Check on the level sequence
5. Load Layout Existing
6. Check on the level sequence again, the assets loaded from the layout existing loader are added into that.
> Spawned actors loaded from layout existing should be added into level sequence for the layout

- client/ayon_unreal/api/lib.py
Resolve https://github.com/ynput/ayon-unreal/issues/144
This PR is to make sure the correct frame range of camera cut or animation sequence when they are imported by using connect action in scene inventory.
This is a temporary fix only and it would be restored to use the actual frame range once Epic has fixed the incorrect frame range when the asset has been imported.
2. Load Layout/Camera/Animation
3. Use connect action by selecting layout/camera/animation containers
> Make sure the frame range of camera cut/animation sequence are correct when using connect action

- client/ayon_unreal/api/plugin.py
- client/ayon_unreal/plugins/load/load_layout.py
- client/ayon_unreal/plugins/load/load_layout_existing.py
This PR is to add backward compatibility for json layout to avoid the error from the missing data of "extension" in the old published layout.
n/a.
2. Load Layout with both old/new published layout
3. Should be working
> Backward compatibility for json layout without extension as data

- client/ayon_unreal/api/pipeline.py
- client/ayon_unreal/plugins/load/load_image_png.py
- client/ayon_unreal/plugins/load/load_layout.py
- client/ayon_unreal/plugins/load/load_layout_existing.py
- client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
- client/ayon_unreal/plugins/publish/extract_camera.py
- client/ayon_unreal/plugins/publish/validate_camera_tracks.py
Implement the backward compatibility function for `get_master_tracks` so that the Ayon plugins can be used across different UE versions regarding to the update of 5.5
Resolve https://github.com/ynput/ayon-unreal/issues/162
n/a
1. Test Unreal with this branch (Like loading, publishing etc.)
> Implement function to get tracks for different UE version

- client/ayon_unreal/api/tools_ui.py
Improve the order of the ayon plugins as mentioned in https://github.com/ynput/ayon-unreal/issues/154
2. The order of the ayon plugins should be following the screenshot as shown in https://github.com/ynput/ayon-unreal/issues/154
> Improve the order of the ayon plugins

- client/ayon_unreal/ue_workers.py
This PR is to fix the issue of getting struck at the indefinite loop of pre-workfile preparation(aka Project building) in Unreal when the users firstly launch Unreal with the new task.
n/a
1. Launch Unreal with the new Task
2. Project should be built successfully and the Ayon plugins should be working
> Emit action for building unreal workfile project preparation

- client/ayon_unreal/plugins/load/load_layout.py
This PR is to make sure the correct variable name has been used for syncing the force-loaded enabling function from ayon setting
n/a
1. Go to enable `ayon+settings://unreal/import_settings/force_loaded`
2. Launch Unreal
3. You can find the enable button in the loader and overriding representation type should be working.
> Use correct variable for syncing the force-loaded enable button

- client/ayon_unreal/plugins/load/load_alembic_animation.py
- client/ayon_unreal/plugins/load/load_geometrycache_abc.py
- client/ayon_unreal/plugins/load/load_layout.py
- client/ayon_unreal/plugins/load/load_skeletalmesh_abc.py
- client/ayon_unreal/plugins/load/load_staticmesh_abc.py
- server/import_settings.py
This PR is to backport load transform to older UE versions(4.27), and the new alembic conversion presets supports in Unreal 5. 
https://dev.epicgames.com/documentation/en-us/unreal-engine/python-api/class/AbcConversionPreset?application_version=5.0#unreal.AbcConversionPreset 
Also it introduces the custom alembic conversion presets of which user can choose to set it in ayon settings if the transform is still not what they want. 
Resolve #179 
Please install and build addon with this branch to update the settings
Test it in 5.1 if possible
1. Try the default alembic presets
2. Load Asset in alembic format (Animation, PointCache, Model, Layout)
3. Switch the alembic presets to `custom`
4. Load Asset in alembic format (Animation, PointCache, Model, Layout)
> Backport load transform to older UE versions

- client/ayon_unreal/plugins/publish/create_farm_render_instances.py
This PR is to add `render` as families into the farm render collector to avoid the bug encountered when the instances other than render instance are passing through the collector.
Resolve https://github.com/ynput/ayon-unreal/issues/189
n/a
1. Create any instance other than render instance
2. Publish
> Add render as families into the farm render collector

- client/ayon_unreal/plugins/load/load_animation.py
Fix https://github.com/ynput/ayon-unreal/issues/191
This PR is to make sure the correct x rotation of the animation sequence when performing connect action with layout and animation product in fbx.
n/a
1. Launch Unreal in the launcher which installed with the built addon of this branch
2. Load Layout and fbx animation
3. Go to manage
4. Select layout and fbx animation container and perform connect action.
> Adjustment of the orientation for fbx animation import in 5.5

- client/ayon_unreal/plugins/load/load_image_png.py
- client/ayon_unreal/plugins/load/load_staticmesh_fbx.py
- server/import_settings.py
This PR is to remove the custom pipeline path for the current interchange workflow of importing asset. Users/System can decide which path to use for the interchange workflow.
n/a
1. Enable `ayon+settings://unreal/import_settings/interchange/enabled`
2. Load static mesh in fbx or image in Unreal
> Use interchange pipeline path in ayon setting for interchange import workflow

- client/ayon_unreal/api/plugin.py
Removed `six` module usage.
I don't understand why `Loader` does inherit from `ABC`, because it does not have any `abstractmethod` defined?
> Chore: Removed usage of 'six'

- client/ayon_unreal/hooks/pre_workfile_preparation.py
Fixes engine path on MacOS to start unreal project from Launcher
On macOS it's 6 levels up as the executable lives under ./UnrealEditor.app/Contents/MacOS/UnrealEditor
> Fixes engine path on MacOS

- client/ayon_unreal/ue_workers.py
This PR is to make sure Ayon plugin from fab works with the unreal integration 
Resolve https://github.com/ynput/ayon-unreal/issues/204
Try both scenarios of downloading plugins from fab or building plugins from bat file.
1. Try both scenarios of downloading plugins from fab or building plugins from bat file.
2. Launch Unreal
> Make sure ayon plugin from fab is also working with unreal integration

- client/ayon_unreal/plugins/load/load_animation.py
This part of the code looks at the currently loaded rigs in unreal and finds the one with the same id as rig that created the animation. It creates a list of rigs used from the animation entity and then checks the loaded rigs for a match.
How this was set up it would try to use any of the rigs that did not match.
Fixes #198
Select corect skeleton when importing FBX Animation
1. import rig to unreal
2. create one or more animation in maya with rig
3. import animation(s) to unreal without having anything selected.
4. It should select the correct skeleton for all the animations.
> fix: correct condition to check if container parent is in rigs

- client/ayon_unreal/plugins/publish/validate_camera_tracks.py
This PR is to fix the incorrect import of validate camera tracks
Resolve https://github.com/ynput/ayon-unreal/issues/210
n/a
2. Create and publish camera instance
> Fix the incorrect import of validate camera tracks 

- client/ayon_unreal/addon.py
Remove usage of the walrus operator (`:=`) in addon as it breaks python 3.7 hosts.
The walrus operator was introduced in Python 3.8. Since addon logic is executed outside AYON process too, this is crashing when running on 3.7 based hosts. It is probably cosmetic, but it pollutes error logs in those hosts. Until complete support for 3.7 is dropped, we shouldn't use it.
Unreal addon should work as expected, no mentions of crashing `addon.py` when running python 3.7 hosts (like older Maya, 3dequalizer, Mocha 2022, etc.)
> :bug: remove walrus operator

- client/ayon_unreal/api/pipeline.py
This PR is to ensure asset level map would be added into the Project Level Map during layout load, as if in the past
n/a 
2. Load multiple Layout
3. Open your Project level map(for example if your project name is `Hello`, it should be named as`/Game/Ayon/Hello_map.Hello_map`
4. Layout loading from your asset level should be showed as children level of the Persistent level in level editor
> Asset Level map should be added into Project Level Map during layout load

- client/ayon_unreal/api/tools_ui.py
- client/ayon_unreal/hooks/pre_workfile_preparation.py
- server/settings.py
Add change context dialog and allow Unreal Engine to run without pre-created project. This will allow to open/create projects via Unreal projects dialog and still use AYON tools from within Unreal.
When the option to enable automatic project creation is disabled and Unreal cannot find existing project using resolved Anatomy template, this will run Unreal Editor without any project set. Unreal will popup the *"new project"* window where you can create new project based on templates or select existing project. When you then open existing one or create new one, Unreal Editor will restart and open selected project. There is now the option to see and change current context.
This feature is also adding new option to the project creation settings - *Force existing project*. When this option is …
> Add change context dialog

- client/ayon_unreal/hooks/pre_workfile_preparation.py
- server/settings.py
This PR is to support users can put the directory of existing unreal project, they can migrate that project to the Ayon unreal-specific work directory and becomes the uproject which can be managed by Ayon
This needs to be used/valid along with `ayon+settings://unreal/project_setup/allow_project_creation` on
Resolve https://github.com/ynput/ayon-unreal/issues/240
We should decide if this should be task-type based, which existing uproject is migrated based upon the task type.
1. Make sure you have existing uproject outside the Ayon directory.
2. Fill in the directory where you stored your uproject in `ayon+settings://unreal/project_setup/existing_uproject_directory`
3. Launch Unreal with the task which does not have unreal project created.
4. Should be all working.
> Supports to use existing uproject for project creation

- client/ayon_unreal/api/rendering.py
- client/ayon_unreal/plugins/create/create_render.py
- client/ayon_unreal/plugins/publish/create_farm_render_instances.py
Select Movie Render Queue render configs on render instance creation. No need to set hardcoded paths in the Settings.
1. Save Render Presets to `/Game/Ayon`
2. When creating render instance, or editing it, you should be able to select them
> Use render presets on instance instead of settings values

- client/ayon_unreal/lib.py
This PR is to ensure the project settings should be gotten during project creation to avoid `current project is not set`.
Resolve https://github.com/ynput/ayon-unreal/issues/249
n/a
1. Enable `ayon+settings://unreal/project_setup/allow_project_creation`
2. Launch Unreal with the task does not include/involve any unreal project
> Getting valid project settings during project creation
